language: node_js

node_js:
  - 10.4.1

os:
  - windows
  - linux
  - osx
  
script:
  - npm run lint
  - npm run build

deploy:
  - provider: releases
    api_key: $GH_OAUTH
    file_glob: true
    file: dist/*
    overwrite: true
    prerelease: true
    skip_cleanup: true
    on:
      branch: travis
  - provider: releases
    api_key: $GH_OAUTH
    file_glob: true
    file: dist/*
    skip_cleanup: true
    on:
      tags: true
